[2025-07-24T07:54:49.283+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T07:54:45.416701+00:00 [queued]>
[2025-07-24T07:54:49.287+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T07:54:45.416701+00:00 [queued]>
[2025-07-24T07:54:49.288+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-24T07:54:49.331+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): kafka_to_bronze> on 2025-07-24 07:54:45.416701+00:00
[2025-07-24T07:54:49.334+0000] {standard_task_runner.py:60} INFO - Started process 591 to run task
[2025-07-24T07:54:49.336+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bis_pipeline_dag', 'kafka_to_bronze', 'manual__2025-07-24T07:54:45.416701+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/bis_pipeline_dag.py', '--cfg-path', '/tmp/tmpnmxaetha']
[2025-07-24T07:54:49.338+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask kafka_to_bronze
[2025-07-24T07:54:49.400+0000] {task_command.py:423} INFO - Running <TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T07:54:45.416701+00:00 [running]> on host 97c5d068d3eb
[2025-07-24T07:54:49.516+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='bis_pipeline_dag' AIRFLOW_CTX_TASK_ID='kafka_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T07:54:45.416701+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T07:54:45.416701+00:00'
[2025-07-24T07:54:49.519+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-24T07:54:49.521+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec spark-master spark-submit --master spark://spark-master:7077 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.4 /app/bronze.py']
[2025-07-24T07:54:49.532+0000] {subprocess.py:86} INFO - Output:
[2025-07-24T07:54:49.542+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-07-24T07:54:49.543+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-24T07:54:49.551+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-24T07:54:49.553+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=bis_pipeline_dag, task_id=kafka_to_bronze, execution_date=20250724T075445, start_date=20250724T075449, end_date=20250724T075449
[2025-07-24T07:54:49.609+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task kafka_to_bronze (Bash command failed. The command returned a non-zero exit code 1.; 591)
[2025-07-24T07:54:49.629+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T07:54:49.645+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
