[2025-07-25T01:08:45.048+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze manual__2025-07-25T01:08:43.818377+00:00 [queued]>
[2025-07-25T01:08:45.052+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze manual__2025-07-25T01:08:43.818377+00:00 [queued]>
[2025-07-25T01:08:45.052+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-25T01:08:45.129+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): collect_bronze> on 2025-07-25 01:08:43.818377+00:00
[2025-07-25T01:08:45.132+0000] {standard_task_runner.py:60} INFO - Started process 351 to run task
[2025-07-25T01:08:45.135+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bis_pipeline_dag', 'collect_bronze', 'manual__2025-07-25T01:08:43.818377+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/bis_pipeline_dag.py', '--cfg-path', '/tmp/tmpoqykj_ec']
[2025-07-25T01:08:45.137+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask collect_bronze
[2025-07-25T01:08:45.225+0000] {task_command.py:423} INFO - Running <TaskInstance: bis_pipeline_dag.collect_bronze manual__2025-07-25T01:08:43.818377+00:00 [running]> on host 57edae2a536c
[2025-07-25T01:08:45.353+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bis_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T01:08:43.818377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T01:08:43.818377+00:00'
[2025-07-25T01:08:45.354+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-25T01:08:45.354+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /dags/kafka/api_producer.py']
[2025-07-25T01:08:45.361+0000] {subprocess.py:86} INFO - Output:
[2025-07-25T01:08:45.374+0000] {subprocess.py:93} INFO - python: can't open file '/dags/kafka/api_producer.py': [Errno 2] No such file or directory
[2025-07-25T01:08:45.376+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-25T01:08:45.384+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-25T01:08:45.385+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=bis_pipeline_dag, task_id=collect_bronze, execution_date=20250725T010843, start_date=20250725T010845, end_date=20250725T010845
[2025-07-25T01:08:45.432+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task collect_bronze (Bash command failed. The command returned a non-zero exit code 2.; 351)
[2025-07-25T01:08:45.473+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-25T01:08:45.487+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
