[2025-07-24T07:55:38.102+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T07:55:34.051925+00:00 [queued]>
[2025-07-24T07:55:38.106+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T07:55:34.051925+00:00 [queued]>
[2025-07-24T07:55:38.106+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-24T07:55:38.149+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): kafka_to_bronze> on 2025-07-24 07:55:34.051925+00:00
[2025-07-24T07:55:38.151+0000] {standard_task_runner.py:60} INFO - Started process 615 to run task
[2025-07-24T07:55:38.154+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bis_pipeline_dag', 'kafka_to_bronze', 'manual__2025-07-24T07:55:34.051925+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/bis_pipeline_dag.py', '--cfg-path', '/tmp/tmpujtpneb0']
[2025-07-24T07:55:38.155+0000] {standard_task_runner.py:88} INFO - Job 19: Subtask kafka_to_bronze
[2025-07-24T07:55:38.252+0000] {task_command.py:423} INFO - Running <TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T07:55:34.051925+00:00 [running]> on host 97c5d068d3eb
[2025-07-24T07:55:38.357+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='bis_pipeline_dag' AIRFLOW_CTX_TASK_ID='kafka_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T07:55:34.051925+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T07:55:34.051925+00:00'
[2025-07-24T07:55:38.357+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-24T07:55:38.358+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec spark-master spark-submit --master spark://spark-master:7077 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.4 /app/bronze.py']
[2025-07-24T07:55:38.364+0000] {subprocess.py:86} INFO - Output:
[2025-07-24T07:55:38.373+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-07-24T07:55:38.374+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-24T07:55:38.382+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-24T07:55:38.383+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=bis_pipeline_dag, task_id=kafka_to_bronze, execution_date=20250724T075534, start_date=20250724T075538, end_date=20250724T075538
[2025-07-24T07:55:38.414+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 19 for task kafka_to_bronze (Bash command failed. The command returned a non-zero exit code 1.; 615)
[2025-07-24T07:55:38.446+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T07:55:38.461+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
