[2025-07-24T06:34:53.537+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze manual__2025-07-24T06:29:51.666715+00:00 [queued]>
[2025-07-24T06:34:53.541+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze manual__2025-07-24T06:29:51.666715+00:00 [queued]>
[2025-07-24T06:34:53.542+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-24T06:34:53.576+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): collect_bronze> on 2025-07-24 06:29:51.666715+00:00
[2025-07-24T06:34:53.579+0000] {standard_task_runner.py:60} INFO - Started process 391 to run task
[2025-07-24T06:34:53.581+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bis_pipeline_dag', 'collect_bronze', 'manual__2025-07-24T06:29:51.666715+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/bis_pipeline_dag.py', '--cfg-path', '/tmp/tmpkh9ndhvh']
[2025-07-24T06:34:53.583+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask collect_bronze
[2025-07-24T06:34:53.651+0000] {task_command.py:423} INFO - Running <TaskInstance: bis_pipeline_dag.collect_bronze manual__2025-07-24T06:29:51.666715+00:00 [running]> on host 8130fb364860
[2025-07-24T06:34:53.731+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='bis_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T06:29:51.666715+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T06:29:51.666715+00:00'
[2025-07-24T06:34:53.731+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-24T06:34:53.732+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /producer/api_producer.py']
[2025-07-24T06:34:53.738+0000] {subprocess.py:86} INFO - Output:
[2025-07-24T06:34:55.905+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-24T06:34:55.905+0000] {subprocess.py:93} INFO -   File "/producer/api_producer.py", line 9, in <module>
[2025-07-24T06:34:55.905+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(
[2025-07-24T06:34:55.905+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 481, in __init__
[2025-07-24T06:34:55.905+0000] {subprocess.py:93} INFO -     client = self.config['kafka_client'](
[2025-07-24T06:34:55.905+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 262, in __init__
[2025-07-24T06:34:55.905+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version()
[2025-07-24T06:34:55.905+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 1074, in check_version
[2025-07-24T06:34:55.905+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2025-07-24T06:34:55.905+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-07-24T06:34:55.934+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-24T06:34:55.943+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-24T06:34:55.944+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=bis_pipeline_dag, task_id=collect_bronze, execution_date=20250724T062951, start_date=20250724T063453, end_date=20250724T063455
[2025-07-24T06:34:56.013+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task collect_bronze (Bash command failed. The command returned a non-zero exit code 1.; 391)
[2025-07-24T06:34:56.044+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T06:34:56.137+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
