[2025-07-24T08:14:45.774+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T08:14:42.089053+00:00 [queued]>
[2025-07-24T08:14:45.779+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T08:14:42.089053+00:00 [queued]>
[2025-07-24T08:14:45.779+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-24T08:14:45.811+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): kafka_to_bronze> on 2025-07-24 08:14:42.089053+00:00
[2025-07-24T08:14:45.814+0000] {standard_task_runner.py:60} INFO - Started process 936 to run task
[2025-07-24T08:14:45.816+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bis_pipeline_dag', 'kafka_to_bronze', 'manual__2025-07-24T08:14:42.089053+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/bis_pipeline_dag.py', '--cfg-path', '/tmp/tmpunl3qrvz']
[2025-07-24T08:14:45.817+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask kafka_to_bronze
[2025-07-24T08:14:45.880+0000] {task_command.py:423} INFO - Running <TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T08:14:42.089053+00:00 [running]> on host 97c5d068d3eb
[2025-07-24T08:14:45.989+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='bis_pipeline_dag' AIRFLOW_CTX_TASK_ID='kafka_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T08:14:42.089053+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T08:14:42.089053+00:00'
[2025-07-24T08:14:45.989+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-24T08:14:45.990+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec spark-master spark-submit --master spark://spark-master:7077 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.4 /app/bronze.py']
[2025-07-24T08:14:45.995+0000] {subprocess.py:86} INFO - Output:
[2025-07-24T08:14:46.004+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-07-24T08:14:46.004+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-24T08:14:46.012+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-24T08:14:46.013+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=bis_pipeline_dag, task_id=kafka_to_bronze, execution_date=20250724T081442, start_date=20250724T081445, end_date=20250724T081446
[2025-07-24T08:14:46.044+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 28 for task kafka_to_bronze (Bash command failed. The command returned a non-zero exit code 1.; 936)
[2025-07-24T08:14:46.068+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T08:14:46.082+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
