[2025-07-24T06:05:02.629+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T05:00:00+00:00 [queued]>
[2025-07-24T06:05:02.634+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T05:00:00+00:00 [queued]>
[2025-07-24T06:05:02.634+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-24T06:05:02.675+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): collect_bronze> on 2025-07-24 05:00:00+00:00
[2025-07-24T06:05:02.678+0000] {standard_task_runner.py:60} INFO - Started process 285 to run task
[2025-07-24T06:05:02.681+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bis_pipeline_dag', 'collect_bronze', 'scheduled__2025-07-24T05:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/bis_pipeline_dag.py', '--cfg-path', '/tmp/tmp5w_xpe0x']
[2025-07-24T06:05:02.683+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask collect_bronze
[2025-07-24T06:05:02.757+0000] {task_command.py:423} INFO - Running <TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T05:00:00+00:00 [running]> on host e9ea48abe9b7
[2025-07-24T06:05:02.847+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='bis_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T05:00:00+00:00'
[2025-07-24T06:05:02.848+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-24T06:05:02.848+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /producer/api_producer.py']
[2025-07-24T06:05:02.854+0000] {subprocess.py:86} INFO - Output:
[2025-07-24T06:05:02.929+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-24T06:05:02.929+0000] {subprocess.py:93} INFO -   File "/producer/api_producer.py", line 3, in <module>
[2025-07-24T06:05:02.929+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-07-24T06:05:02.929+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-07-24T06:05:02.937+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-24T06:05:02.945+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-24T06:05:02.947+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=bis_pipeline_dag, task_id=collect_bronze, execution_date=20250724T050000, start_date=20250724T060502, end_date=20250724T060502
[2025-07-24T06:05:02.988+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task collect_bronze (Bash command failed. The command returned a non-zero exit code 1.; 285)
[2025-07-24T06:05:03.025+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T06:05:03.039+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T06:13:46.074+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T05:00:00+00:00 [queued]>
[2025-07-24T06:13:46.079+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T05:00:00+00:00 [queued]>
[2025-07-24T06:13:46.079+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-24T06:13:46.129+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): collect_bronze> on 2025-07-24 05:00:00+00:00
[2025-07-24T06:13:46.132+0000] {standard_task_runner.py:60} INFO - Started process 242 to run task
[2025-07-24T06:13:46.134+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bis_pipeline_dag', 'collect_bronze', 'scheduled__2025-07-24T05:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/bis_pipeline_dag.py', '--cfg-path', '/tmp/tmplzqfsw5d']
[2025-07-24T06:13:46.136+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask collect_bronze
[2025-07-24T06:13:46.203+0000] {task_command.py:423} INFO - Running <TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T05:00:00+00:00 [running]> on host 72ae0ddbb41b
[2025-07-24T06:13:46.297+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='bis_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T05:00:00+00:00'
[2025-07-24T06:13:46.298+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-24T06:13:46.298+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /producer/api_producer.py']
[2025-07-24T06:13:46.304+0000] {subprocess.py:86} INFO - Output:
[2025-07-24T06:13:46.378+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-24T06:13:46.379+0000] {subprocess.py:93} INFO -   File "/producer/api_producer.py", line 3, in <module>
[2025-07-24T06:13:46.379+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-07-24T06:13:46.379+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-07-24T06:13:46.388+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-24T06:13:46.396+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-24T06:13:46.398+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=bis_pipeline_dag, task_id=collect_bronze, execution_date=20250724T050000, start_date=20250724T061346, end_date=20250724T061346
[2025-07-24T06:13:46.454+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task collect_bronze (Bash command failed. The command returned a non-zero exit code 1.; 242)
[2025-07-24T06:13:46.487+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T06:13:46.503+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T06:32:41.562+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T05:00:00+00:00 [queued]>
[2025-07-24T06:32:41.567+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T05:00:00+00:00 [queued]>
[2025-07-24T06:32:41.567+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-24T06:32:41.611+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): collect_bronze> on 2025-07-24 05:00:00+00:00
[2025-07-24T06:32:41.614+0000] {standard_task_runner.py:60} INFO - Started process 363 to run task
[2025-07-24T06:32:41.616+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bis_pipeline_dag', 'collect_bronze', 'scheduled__2025-07-24T05:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/bis_pipeline_dag.py', '--cfg-path', '/tmp/tmprlk04790']
[2025-07-24T06:32:41.618+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask collect_bronze
[2025-07-24T06:32:41.689+0000] {task_command.py:423} INFO - Running <TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T05:00:00+00:00 [running]> on host 8130fb364860
[2025-07-24T06:32:41.781+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='bis_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T05:00:00+00:00'
[2025-07-24T06:32:41.781+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-24T06:32:41.782+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /producer/api_producer.py']
[2025-07-24T06:32:41.788+0000] {subprocess.py:86} INFO - Output:
[2025-07-24T06:32:43.952+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-24T06:32:43.953+0000] {subprocess.py:93} INFO -   File "/producer/api_producer.py", line 9, in <module>
[2025-07-24T06:32:43.953+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(
[2025-07-24T06:32:43.953+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 481, in __init__
[2025-07-24T06:32:43.954+0000] {subprocess.py:93} INFO -     client = self.config['kafka_client'](
[2025-07-24T06:32:43.954+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 262, in __init__
[2025-07-24T06:32:43.954+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version()
[2025-07-24T06:32:43.954+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 1074, in check_version
[2025-07-24T06:32:43.954+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2025-07-24T06:32:43.954+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-07-24T06:32:43.978+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-24T06:32:43.985+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-24T06:32:43.987+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=bis_pipeline_dag, task_id=collect_bronze, execution_date=20250724T050000, start_date=20250724T063241, end_date=20250724T063243
[2025-07-24T06:32:44.032+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task collect_bronze (Bash command failed. The command returned a non-zero exit code 1.; 363)
[2025-07-24T06:32:44.042+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T06:32:44.059+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
